### ISSUE TITLE
LoadError: page_layout

### ISSUE THREAD

**Issue by joaomsbravo** [foundercatalyst/docxify#2]
I am having the following error when I try to install the gem:

`LoadError: cannot load such file -- /usr/local/bundle/gems/docxify-0.0.8/lib/docxify/element/page_layout (LoadError)`

**Comment by andyjeffries** [comment]
Sorry, try upgrading to 0.0.9 or later.  https://github.com/foundercatalyst/docxify/blob/master/CHANGELOG.md#009

I wasn't aware anyone was using this gem yet :-) I wrote it for internal use at my company and we aren't even using it yet.
